services:
  kleinanzeigenadalert:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_PATH=/app/data/database.db
    env_file:
      - .env.docker-compose