services:
  kleinanzeigenadalert:
    image: sirreini1/kleinanzeigenadalert:latest
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DB_PATH=/app/data/database.db
    env_file:
      - .env.docker-compose
    volumes:
      - kleinanzeigenadalert_data:/app/data

volumes:
  kleinanzeigenadalert_data: